name: Backofficeお知らせ用 Issue Form
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * 送付希望日程や原稿の内容を明記してください。
        * 関係者や目的に関する情報も提供してください。

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false


  - type: input
    id: manuscript
    attributes:
      label: タイトル
      description: 原稿のタイトルを入力してください。
      placeholder:
    validations:
      required: true

  - type: textarea
    id: title
    attributes:
      label: 原稿
      description: 原稿の内容を入力してください。
      placeholder:
    validations:
      required: true

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日程
      description: 送付を希望する日程を入力してください。
      placeholder: 
    validations:
      required: true

  - type: dropdown
    id: market
    attributes:
      label: 対象マーケット
      description: 対象マーケットを選んでください。
      options:
      - label: B2C
      - label: B2B
      - label: 全て
        required: true


  - type: dropdown
    id: grade
    attributes:
      label: 対象学年
      description: 対象学年を選んでください。
      options:
      - label: 高卒生／予備校生（22歳以下）
      - label: 高校3年生
      - label: 高校2年生
      - label: 高校1年生
      - label: 中学3年生
      - label: 中学2年生
      - label: 中学1年生
      - label: 小学6年生
      - label: 小学5年生
      - label: 小学4年生
      - label: 小学3年生
      - label: 小学2年生
      - label: 小学1年生
        required: true

  - type: dropdown
    id: plan
    attributes:
      label: 対象の契約プラン
      description: 対象の契約プランを選んでください。
      options:
      - label: 無料会員
      - label: ベーシック(basic)
      - label: 合格特訓コース(online_coaching)
      - label: 中学個別指導コース(yui)
      - label: シン個別
        required: true

      - type: dropdown
    id: plan
    attributes:
      label: リスト抽出有無
      description: リスト抽出の有無を選択してください。
      options:
      - label: あり
      - label: なし
        required: true


