issue_form:
  fields:
    - name:
        type: text
        label: "Name"
        placeholder: "Enter your name"

    - campaign_type:
        type: checkbox
        label: "Campaign type"
        options:
          - "Option 1"
          - "Option 2"
          - "Option 3"

    - show_to_aya_early_discountable_users:
        type: text
        label: "Show to aya early discountable users"
        placeholder: "Enter details here"

    - teacher_content_url:
        type: text
        label: "Teacher content url"
        placeholder: "Enter URL here"

    - teacher_banner_url:
        type: text
        label: "Teacher Banner URL"
        placeholder: "Enter URL here"

    - student_content_url:
        type: text
        label: "Student content url"
        placeholder: "Enter URL here"

    - student_banner_url:
        type: text
        label: "Student Banner URL"
        placeholder: "Enter URL here"

    - aya_grades:
        type: dropdown
        label: "Aya Grades"
        options:
          - "Grade 1"
          - "Grade 2"
          - "Grade 3"

    - aya_market:
        type: checkbox
        label: "Aya market"
        options:
          - "Market Option 1"
          - "Market Option 2"

    - license_ids:
        type: checkbox
        label: "License ids"
        options:
          - "License 1"
          - "License 2"
          - "License 3"

    - subscription_status:
        type: dropdown
        label: "Subscription status"
        options:
          - "Active"
          - "Inactive"
          - "Pending"

    - excluded_license:
        type: dropdown
        label: "Excluded license"
        options:
          - "License A"
          - "License B"

    - show_to_trial_users:
        type: checkbox
        label: "Show to trial users"

    - timezone:
        type: dropdown
        label: "Timezone"
        options:
          - "UTC"
          - "GMT"
          - "PST"
          - "EST"

    - start_date:
        type: dropdown
        label: "Start Date"
        options:
          - "Date Option 1"
          - "Date Option 2"

    - end_date:
        type: dropdown
        label: "End Date"
        options:
          - "Date Option 1"
          - "Date Option 2"

    - show_to_all_users:
        type: checkbox
        label: "Show to all users"
