name: Backofficeお知らせ用 Issue Form
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * 送付希望日程や原稿の内容を明記してください。
        * 関係者や目的に関する情報も提供してください。

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false


  - type: input
    id: manuscript
    attributes:
      label: タイトル
      description: 原稿のタイトルを入力してください。
      placeholder:
    validations:
      required: true

  - type: textarea
    id: title
    attributes:
      label: 原稿
      description: 原稿の内容を入力してください。
      placeholder:
    validations:
      required: true

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日程
      description: 送付を希望する日程を入力してください。
      placeholder: 
    validations:
      required: true

        - type: checkboxes
    id: target_grade
    attributes:
      label: 対象学年
    options:
      - label: 高卒生／予備校生（22歳以下）
        value: high_school_grad
      - label: 高校3年生
        value: high_school_3
      - label: 高校2年生
        value: high_school_2
      - label: 高校1年生
        value: high_school_1
      - label: 中学3年生
        value: middle_school_3
      - label: 中学2年生
        value: middle_school_2
      - label: 中学1年生
        value: middle_school_1
      - label: 小学6年生
        value: elementary_6
      - label: 小学5年生
        value: elementary_5
      - label: 小学4年生
        value: elementary_4
      - label: 小学3年生
        value: elementary_3
      - label: 小学2年生
        value: elementary_2
      - label: 小学1年生
        value: elementary_1




