name: Issue Request Form
description: こちらのフォームに必要事項を入力してください。

title: "[Issue Request]"

body:
  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 山田太郎
      required: false

  - type: input
    id: purpose
    attributes:
      label: 目的
      description: このissueの目的を入力してください。
      placeholder: 新しいマーケティングプランの提案
      required: false

  - type: input
    id: manuscript
    attributes:
      label: 原稿
      description: 原稿を入力してください。
      placeholder: 例: 原稿の内容
      required: true

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日程
      description: 送付を希望する日程を入力してください。
      placeholder: 例: 2023年10月15日
      required: true
