name: Backofficeお知らせ用 Issue Form
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * 送付希望日程や原稿の内容を明記してください。
        * 関係者や目的に関する情報も提供してください。

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false

  - type: textarea
    id: manuscript
    attributes:
      label: 原稿
      description: 原稿の内容を入力してください。
      placeholder:
    validations:
      required: true

  - type: textarea
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
