name: "Issue Form"
description: "Fill out this form to create a new issue."
title: "[ISSUE] "
labels: []
body:
  - type: input
    id: name
    attributes:
      label: "Name"
      placeholder: "Enter your name"

  - type: dropdown
    id: campaign_type
    attributes:
      label: "Campaign type"
      options:
        - "Option 1"
        - "Option 2"
        - "Option 3"

  - type: input
    id: show_to_aya_early_discountable_users
    attributes:
      label: "Show to aya early discountable users"
      placeholder: "Enter details here"

  - type: input
    id: teacher_content_url
    attributes:
      label: "Teacher content url"
      placeholder: "Enter URL here"

