name: Bug Report
description: Report a bug in the project
title: "[BUG] "
labels: bug
body:
  - type: markdown
    attributes:
      value: "## 問題の概要"
  - type: textarea
    id: issue-description
    attributes:
      label: "問題の詳細"
      description: "問題について詳しく説明してください。"
      placeholder: "ここに説明を入力してください..."
      validations:
        required: true
  - type: input
    id: steps-to-reproduce
    attributes:
      label: "再現手順"
      description: "問題を再現する手順を入力してください。"
      placeholder: "ステップ1, ステップ2 ..."
      validations:
        required: true
  - type: input
    id: expected-result
    attributes:
      label: "期待される結果"
      description: "期待される結果を入力してください。"
      placeholder: "期待する動作..."
  - type: input
    id: actual-result
    attributes:
      label: "実際の結果"
      description: "実際に得られた結果を入力してください。"
      placeholder: "実際の動作..."
