name: Backofficeお知らせ用 Issue Form
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - content
body:
  - type: markdown
    attributes:
      value: |
        * 送付希望日程や原稿の内容を明記してください。
        * 関係者や目的に関する情報も提供してください。

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false


  - type: input
    id: manuscript
    attributes:
      label: タイトル
      description: 原稿のタイトルを入力してください。
      placeholder:
    validations:
      required: true

  - type: textarea
    id: title
    attributes:
      label: 原稿
      description: 原稿の内容を入力してください。
      placeholder:
    validations:
      required: true

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日程
      description: 送付を希望する日程を入力してください。
      placeholder: 
    validations:
      required: true

  - type: dropdown
    id: plan
    attributes:
      label: 対象の契約プラン
    options:
      - label: 無料会員
        value: free_member
      - label: ベーシック(basic)
        value: basic
      - label: 合格特訓コース(online_coaching)
        value: online_coaching
      - label: 中学個別指導コース(yui)
        value: yui
      - label: シン個別
        value: shin
      

