name: "Issue Form"
description: "Fill out this form to create a new issue."
title: "[ISSUE] "
labels: []
body:
  - type: input
    id: name
    attributes:
      label: "Name"
      placeholder: "Enter your name"

  - type: dropdown
    id: campaign_type
    attributes:
      label: "Campaign type"
      options:
        - label: "Option 1"
          value: "option_1"
        - label: "Option 2"
          value: "option_2"
        - label: "Option 3"
          value: "option_3"

  - type: input
    id: show_to_aya_early_discountable_users
    attributes:
      label: "Show to aya early discountable users"
      placeholder: "Enter details here"

  - type: input
    id: teacher_content_url
    attributes:
      label: "Teacher content url"
      placeholder: "Enter URL here"

  - type: input
    id: teacher_banner_url
    attributes:
      label: "Teacher Banner URL"
      placeholder: "Enter URL here"

  - type: input
    id: student_content_url
    attributes:
      label: "Student content url"
      placeholder: "Enter URL here"

  - type: input
    id: student_banner_url
    attributes:
      label: "Student Banner URL"
      placeholder: "Enter URL here"

  - type: dropdown
    id: aya_grades
    attributes:
      label: "Aya Grades"
      options:
        - label: "Grade 1"
          value: "grade_1"
        - label: "Grade 2"
          value: "grade_2"
        - label: "Grade 3"
          value: "grade_3"

  - type: checkboxes
    id: aya_market
    attributes:
      label: "Aya market"
      options:
        - label: "Market Option 1"
          value: "market_option_1"
        - label: "Market Option 2"
          value: "market_option_2"

  - type: checkboxes
    id: license_ids
    attributes:
      label: "License ids"
      options:
        - label: "License 1"
          value: "license_1"
        - label: "License 2"
          value: "license_2"
        - label: "License 3"
          value: "license_3"

  - type: dropdown
    id: subscription_status
    attributes:
      label: "Subscription status"
      options:
        - label: "Active"
          value: "active"
        - label: "Inactive"
          value: "inactive"
        - label: "Pending"
          value: "pending"

  - type: dropdown
    id: excluded_license
    attributes:
      label: "Excluded license"
      options:
        - label: "License A"
          value: "license_a"
        - label: "License B"
          value: "license_b"

  - type: dropdown
    id: show_to_trial_users
    attributes:
      label: "Show to trial users"
      options:
        - label: "Yes"
          value: "yes"
        - label: "No"
          value: "no"

  - type: dropdown
    id: timezone
    attributes:
      label: "Timezone"
      options:
        - label: "UTC"
          value: "utc"
        - label: "GMT"
          value: "gmt"
        - label: "PST"
          value: "pst"
        - label: "EST"
          value: "est"

  - type: dropdown
    id: start_date
    attributes:
      label: "Start Date"
      options:
        - label: "Date Option 1"
          value: "date_option_1"
        - label: "Date Option 2"
          value: "date_option_2"

  - type: dropdown
    id: end_date
    attributes:
      label: "End Date"
      options:
        - label: "Date Option 1"
          value: "date_option_1"
        - label: "Date Option 2"
          value: "date_option_2"

  - type: dropdown
    id: show_to_all_users
    attributes:
      label: "Show to all users"
      options:
        - label: "Yes"
          value: "yes"
        - label: "No"
          value: "no"
