name: "Simple Issue Form"
description: "Use this form to report an issue or provide feedback."
title: "[ISSUE] "
labels: []
body:
  - type: input
    id: issue_title
    attributes:
      label: "Issue Title"
      placeholder: "Enter a brief title for the issue"

  - type: checkboxes
    id: issue_category
    attributes:
      label: "Select Issue Category"
      options:
        - "Bug"
        - "Feature Request"
        - "Improvement"

  - type: dropdown
    id: priority_level
    attributes:
      label: "Priority Level"
      options:
        - "Low"
        - "Medium"
        - "High"
