name: "Feature Request"
description: "Suggest a new feature for this project"
title: "[Feature]"
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "### Describe the feature"
  - type: input
    id: feature_name
    attributes:
      placeholder: "Feature Name"
      required: true
