name: "Issue Template"
description: "Describe your issue"
title: "Issue Title"
labels: ["bug"]
assignees: ["your-username"]
body:
  - type: markdown
    attributes:
      value: "### Please provide a brief description of the issue."
  - type: input
    id: name
    attributes:
      placeholder: "Name"
      required: true
  # 他のフィールドを追加
