name: Backofficeお知らせ用 親issueテンプレ.yml
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - issue forms FMT
body:

  - type: checkboxes
    id: user_id
    attributes:
      label: リスト入稿有無
      description: >
        リスト入稿の有無を選択してください
      options:
      - label: リスト入稿あり
      - label: リスト入稿なし
        required: false
      
  - type: input
    id: channel_name
    attributes:
      label: 配信チャネル
      description: 配信チャネルを記載してください
      placeholder: 
    validations:
      required: true
      
  - type: input
    id: purpose
    attributes:
      label: 目的
      description: 施策の目的を記載してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日時
      description: 送付を希望する日程を入力してください。（※半角数字のみ 例：2025/05/19 00:00）
      placeholder: 
    validations:
      required: true
        
  - type: checkboxes
    id: aya_market
    attributes:
      label: Aya Market
      description: 対象マーケットを選んでください。必ず１つ以上選択してください。
      options:
      - label: B2C
      - label: B2B
      - label: 全て
        required: false

  - type: checkboxes
    id: aya_grade_ids
    attributes:
      label: Aya Grades
      description: 対象学年を選んでください。※配信日時点の学年を指定してください
      options:
      - label: 高卒生／予備校生（22歳以下）
      - label: 高校3年生
      - label: 高校2年生
      - label: 高校1年生
      - label: 中学3年生
      - label: 中学2年生
      - label: 中学1年生
      - label: 小学6年生
      - label: 小学5年生
      - label: 小学4年生
      - label: 小学3年生
      - label: 小学2年生
      - label: 小学1年生
        required: false

  - type: checkboxes
    id: license_ids
    attributes:
      label: Licenses
      description: >
        対象の契約プランを選んでください。必ず１つ以上選択してください。
      options:
      - label: paid
      - label: unpaid
      - label: all
        required: false

