name: Backofficeお知らせ用 親issueテンプレ.yml
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - issue forms FMT
body:

  - type: checkboxes
    id: user_id
    attributes:
      label: リスト入稿有無
      description: >
        リスト入稿の有無を選択してください
      options:
      - label: リスト入稿あり
      - label: リスト入稿なし
        required: false
      
  - type: input
    id: channel_name
    attributes:
      label: 配信チャネル
      description: 配信チャネルを記載してください
      placeholder: 
    validations:
      required: true
      
  - type: input
    id: purpose
    attributes:
      label: 目的
      description: 施策の目的を記載してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日時
      description: 送付を希望する日程を入力してください。（※半角数字のみ 例：2025/05/19 00:00）
      placeholder: 
    validations:
      required: true
        
  - type: checkboxes
    id: aya_market
    attributes:
      label: Aya Market
      description: 対象マーケットを選んでください。
      options:
      - label: B2C
      - label: B2B
      - label: 全て
        required: false

  - type: checkboxes
    id: aya_grade_ids
    attributes:
      label: Aya Grades
      description: 対象学年を選んでください。※配信日時点の学年を指定してください
      options:
      - label: 高卒生／予備校生（22歳以下）
      - label: 高校3年生
      - label: 高校2年生
      - label: 高校1年生
      - label: 中学3年生
      - label: 中学2年生
      - label: 中学1年生
      - label: 小学6年生
      - label: 小学5年生
      - label: 小学4年生
      - label: 小学3年生
      - label: 小学2年生
      - label: 小学1年生
        required: false

  - type: checkboxes
    id: license_ids
    attributes:
      label: Licenses
      description: 対象の契約プランを選んでください。
      options:
      - label: paid
      - label: unpaid
      - label: all
        required: false

  - type: checkboxes
    id: extraction_reason
    attributes:
      label: データ抽出が必要な理由
      description: >
        抽出が必要な理由を選択してください。
      options:
      - label: 「スタディサプリからのメールマガジンを受け取る」が不許可の会員、B2B2C会員(高校の団体会員)、退会者など通常CRMの対象でない会員にも配信したい場合
      - label: LIVEの事前登録者などスタサプ会員でない人に配信したい場合
      - label: URLパラメーターやキャンペーンコードなど、ひとりひとり異なる情報を含むメールを送りたい場合
      - label: 学習者IDやサポートwebIDで、回答したユーザーの特定が必要な場合（例：アンケートに回答したユーザーに謝礼を送る 等）
      - label: 例外的な時間帯に配信したい場合
      - label: 施策後にデータ部に効果測定を依頼する場合
      - label: Marketoでは指定できないセグメントに送付したい場合
      - label: （お知らせ/ayaWebバナー/aya帯ヘッダーで配信する場合）学年/toCtoB/有料無料 以外のだし分けする
        required: false

  - type: checkboxes
    id: extraction_method
    attributes:
      label: データ抽出方法
      description: 抽出方法を選択してください。
      options:
      - label: Sugar
      - label: データGに依頼
        required: false
