name: お知らせ
description: お知らせを配信したい場合はこちらのフォームを作成してください。
body:

  - type: checkboxes
    id: user_id
    attributes:
      label: リスト入稿有無
      description: >
        リスト入稿の有無を選択してください
      options:
      - label: リスト入稿あり
      - label: リスト入稿なし
        required: true
      
  - type: input
    id: channel_name
    attributes:
      label: 配信チャネル
      description: 配信チャネルを記載してください
      placeholder: 
    validations:
      required: false

  - type: input
    id: title
    attributes:
      label: 件名
      description: 件名を入力してください。
      placeholder:
    validations:
      required: true

  - type: textarea
    id: body
    attributes:
      label: 本文
      description: 本文を入力してください。
      placeholder:
    validations:
      required: true

  - type: input
    id: send_at
    attributes:
      label: 送付希望日時
      description: 送付を希望する日程を入力してください。（※半角数字のみ 例：2025/05/19 00:00）
      placeholder: 
    validations:
      required: true
        
  - type: checkboxes
    id: aya_grade_ids
    attributes:
      label: Aya Grades
      description: 対象学年を選んでください。必ず１つ以上選択してください。
      options:
      - label: 高卒生／予備校生（22歳以下）
      - label: 高校3年生
      - label: 高校2年生
      - label: 高校1年生
      - label: 中学3年生
      - label: 中学2年生
      - label: 中学1年生
      - label: 小学6年生
      - label: 小学5年生
      - label: 小学4年生
      - label: 小学3年生
      - label: 小学2年生
      - label: 小学1年生
        required: false

  - type: input
    id: extraction_conditions
    attributes:
      label: 【データ抽出が必要な場合のみ】以下を埋めてください。お知らせ/ayaWebバナー/aya帯ヘッダーで学年/toCtoB/有料無料 以外のだし分けする際も、データ抽出が必要です。※詳細はk12-CRMマニュアルをご確認ください。
      description: 具体的な抽出条件を記入してください。例：toC、高1～高3、合格特訓契約者のみ
      placeholder: 
    validations:
      required: false

