name: Backofficeお知らせ用 親issueテンプレ.yml
description: お知らせを配信したい場合はこちらのフォームを作成してください。
labels:
  - issue forms FMT
body:

  - type: checkboxes
    id: user_id
    attributes:
      label: リスト入稿有無
      description: >
        リスト入稿の有無を選択してください
      options:
      - label: リスト入稿あり
      - label: リスト入稿なし
        required: false
      
  - type: input
    id: channel_name
    attributes:
      label: 配信チャネル
      description: 配信チャネルを記載してください
      placeholder: 
    validations:
      required: true
      
  - type: input
    id: purpose
    attributes:
      label: 目的
      description: 施策の目的を記載してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: desired_date
    attributes:
      label: 送付希望日時
      description: 送付を希望する日程を入力してください。（※半角数字のみ 例：2025/05/19 00:00）
      placeholder: 
    validations:
      required: true
        
  - type: checkboxes
    id: aya_market
    attributes:
      label: Aya Market
      description: 対象マーケットを選んでください。
      options:
      - label: B2C
      - label: B2B
      - label: 全て
        required: false

  - type: checkboxes
    id: aya_grade_ids
    attributes:
      label: Aya Grades
      description: 対象学年を選んでください。※配信日時点の学年を指定してください
      options:
      - label: 高卒生／予備校生（22歳以下）
      - label: 高校3年生
      - label: 高校2年生
      - label: 高校1年生
      - label: 中学3年生
      - label: 中学2年生
      - label: 中学1年生
      - label: 小学6年生
      - label: 小学5年生
      - label: 小学4年生
      - label: 小学3年生
      - label: 小学2年生
      - label: 小学1年生
        required: false

  - type: checkboxes
    id: license_ids
    attributes:
      label: Licenses
      description: >
        対象の契約プランを選んでください。
      options:
      - label: paid
      - label: unpaid
      - label: all
        required: false

name: データ抽出リクエスト
description: |
  ## 【データ抽出が必要な場合のみ】以下を埋めてください
  お知らせ/ayaWebバナー/aya帯ヘッダーで学年/toCtoB/有料無料 以外のだし分けする際も、データ抽出が必要です。
  ※詳細は[k12-CRMマニュアル](https://docs.google.com/presentation/d/191jyNn0I-Qjl48CXsupLBl1heX4FDyke8-WYeyW_0Zg/edit#slide=id.g343980a66ee_0_86)をご確認ください。

  - type: checkbox
    id: extraction_reason
    label: データ抽出が必要な理由
    options:
      - "「スタディサプリからのメールマガジンを受け取る」が不許可の会員、B2B2C会員(高校の団体会員)、退会者など通常CRMの対象でない会員にも配信したい場合"
      - "LIVEの事前登録者などスタサプ会員でない人に配信したい場合"
      - "URLパラメーターやキャンペーンコードなど、ひとりひとり異なる情報を含むメールを送りたい場合"
      - "学習者IDやサポートwebIDで、回答したユーザーの特定が必要な場合（例：アンケートに回答したユーザーに謝礼を送る 等）"
      - "例外的な時間帯に配信したい場合"
      - "施策後にデータ部に効果測定を依頼する場合"
      - "Marketoでは指定できないセグメントに送付したい場合"
      - "（お知らせ/ayaWebバナー/aya帯ヘッダーで配信する場合）学年/toCtoB/有料無料 以外のだし分けする"

  - type: checkbox
    id: extraction_method
    label: データ抽出方法
    options:
      - "Sugar"
      - "データGに依頼"

  - type: textarea
    id: extraction_conditions
    label: 抽出条件を記載ください
    placeholder: "例：toC、高1～高3、合格特訓契約者のみ"

  - type: file
    id: extraction_capture
    label: 抽出画面のキャプチャを貼る

  - type: checkbox
    id: w_check
    label: 対象者の条件があっているか、領域内でWチェックする
    options:
      - "Wチェックが完了したら✓する"

  - type: text
    id: extraction_issue
    label: 抽出issue
    placeholder: "XXX"

  - type: text
    id: delivery_date
    label: 配信リストの納品日
    placeholder: "YYYY/MM/DD 00:00頃"

  - type: checkbox
    id: user_status
    label: 抽出時のユーザー状態
    options:
      - "CRM通常対象者"
      - "イレギュラー対象者含む"

  - type: checkbox
    id: measurement_needed
    label: 効果計測
    options:
      - "intr有り"
      - "intr無し"

  - type: checkbox
    id: standard_process
    label: 標準プロセスチェック
    options:
      - "標プロ通過済"
      - "標プロ不要"

  - type: checkbox
    id: quality_process
    label: 表示品質プロセスチェック（24/6月より運用開始）
    options:
      - "表示品質チェックセルフチェック済"
      - "表示品質チェックWチェック済"
