name: Backofficeバナー用 Issue Form（リスト入稿あり）
description: バナーを配信したい場合はこちらのフォームを作成してください。
labels:
  - issue forms FMT
body:
  - type: input
    id: purpose
    attributes:
      label: 目的
      description: 施策の目的を記載してください。
      placeholder: 
    validations:
      required: false

  - type: input
    id: stakeholders
    attributes:
      label: 関係者
      description: 関係者の名前や役職などを入力してください。
      placeholder: 
    validations:
      required: false


  - type: input
    id: manuscript
    attributes:
      label: Name
      description: 原稿のタイトルを入力してください。
      placeholder:
    validations:
      required: true

  - type: input
    id: startdate
    attributes:
      label: Start Date
      description: 配信を開始する日程を入力してください。（※半角数字のみ 例：2025/05/19 00:00）
      placeholder:
    validations:
      required: true

  - type: input
    id: enddate
    attributes:
      label: End Date
      description: 配信を終了する日程を入力してください。（※半角数字のみ 例：2025/05/19 00:00）
      placeholder:
    validations:
      required: true

    
  - type: checkboxes
    id: market
    attributes:
      label: Aya Market
      description: 対象マーケットを選んでください。必ず１つ以上選択してください。
      options:
      - label: B2C
      - label: B2B
      - label: 全て
        required: false

  - type: checkboxes
    id: plan
    attributes:
      label: License ids
      description: >
        対象の契約プランを選んでください。必ず１つ以上選択してください。
      options:
      - label: 無料会員
      - label: ベーシック(basic)
      - label: 合格特訓コース(online_coaching)
      - label: 中学個別指導コース(yui)
      - label: シン個別

  - type: input
    id: banne_URL
    attributes:
      label: バナーURL
      description: 
      placeholder:
    validations:
      required: true

  - type: input
    id: file_URL
    attributes:
      label: 画像URL
      description: 
      placeholder:
    validations:
      required: true

  - type: input
    id: targetusers
    attributes:
      label: Target Users
      description: リストの格納先ファイルのパスを記入してください
      placeholder:
    validations:
      required: true


